---
  publishers:
    - queueName: demo
      contentType: binary
      confirm: true
    - queueName: demo-json
      contentType: json
      confirm: true
      schema:
        properties:
          id:
            type: string
          eventStatus:
            enum:
              - IN_PROGRESS
              - PENDING
              - PLANNED
        optionalProperties:
          notes:
            type: string

  consumers:
    - queueName: demo
    - queueName: demo-json
  subscribers:
    - queueName: demo
      target: http://localhost:5555/target
      prefetch: 1
      backoffStrategy: linear
      retries: 4
      retryDelay: 1000
